[workspace]
members = ["runtime", "compiler"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2024"
authors = ["Ed Sweeney <ed@onextent.com>"]
license = "MIT"

[workspace.dependencies]
# Concurrency
may = "0.3"

# Memory management
bumpalo = "3.16"

# System calls
libc = "0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
