[package]
name = "may_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
may = "0.3"

[[bin]]
name = "may_bench"
path = "src/main.rs"

[[bin]]
name = "skynet_native"
path = "src/skynet_native.rs"

[profile.release]
opt-level = 3

[workspace]
