[package]
name = "seq-compiler"
version.workspace = true
edition.workspace = true

[[bin]]
name = "seqc"
path = "src/main.rs"

[dependencies]
seq-runtime = { path = "../runtime" }
clap = { version = "4.5", features = ["derive"] }

[lib]
name = "seqc"
path = "src/lib.rs"
